/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FantasyLeagueRouteImport } from './routes/fantasy-league'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as LiquidityRouteImport } from './routes/liquidity'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as TradeRouteImport } from './routes/trade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyLeagueRoute = FantasyLeagueRouteImport.update({
  id: '/fantasy-league',
  path: '/fantasy-league',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidityRoute = LiquidityRouteImport.update({
  id: '/liquidity',
  path: '/liquidity',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fantasy-league': typeof FantasyLeagueRoute
  '/governance': typeof GovernanceRoute
  '/liquidity': typeof LiquidityRoute
  '/portfolio': typeof PortfolioRoute
  '/trade': typeof TradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fantasy-league': typeof FantasyLeagueRoute
  '/governance': typeof GovernanceRoute
  '/liquidity': typeof LiquidityRoute
  '/portfolio': typeof PortfolioRoute
  '/trade': typeof TradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fantasy-league': typeof FantasyLeagueRoute
  '/governance': typeof GovernanceRoute
  '/liquidity': typeof LiquidityRoute
  '/portfolio': typeof PortfolioRoute
  '/trade': typeof TradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fantasy-league'
    | '/governance'
    | '/liquidity'
    | '/portfolio'
    | '/trade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fantasy-league'
    | '/governance'
    | '/liquidity'
    | '/portfolio'
    | '/trade'
  id:
    | '__root__'
    | '/'
    | '/fantasy-league'
    | '/governance'
    | '/liquidity'
    | '/portfolio'
    | '/trade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FantasyLeagueRoute: typeof FantasyLeagueRoute
  GovernanceRoute: typeof GovernanceRoute
  LiquidityRoute: typeof LiquidityRoute
  PortfolioRoute: typeof PortfolioRoute
  TradeRoute: typeof TradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy-league': {
      id: '/fantasy-league'
      path: '/fantasy-league'
      fullPath: '/fantasy-league'
      preLoaderRoute: typeof FantasyLeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidity': {
      id: '/liquidity'
      path: '/liquidity'
      fullPath: '/liquidity'
      preLoaderRoute: typeof LiquidityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FantasyLeagueRoute: FantasyLeagueRoute,
  GovernanceRoute: GovernanceRoute,
  LiquidityRoute: LiquidityRoute,
  PortfolioRoute: PortfolioRoute,
  TradeRoute: TradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
